-- ============================================================
-- KoriBridge 스키마 업데이트
-- Supabase Dashboard → SQL Editor 에서 실행하세요
-- ============================================================

-- 1. messages 테이블에 read_at 컬럼 추가 (없는 경우에만)
ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS read_at timestamptz DEFAULT NULL;

-- 2. blocked_users 테이블 생성
CREATE TABLE IF NOT EXISTS public.blocked_users (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocker_id  uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  blocked_id  uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  created_at  timestamptz DEFAULT now(),
  UNIQUE (blocker_id, blocked_id)
);

ALTER TABLE public.blocked_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own blocks"
  ON public.blocked_users FOR SELECT
  USING (auth.uid() = blocker_id);

CREATE POLICY "Users can insert own blocks"
  ON public.blocked_users FOR INSERT
  WITH CHECK (auth.uid() = blocker_id);

CREATE POLICY "Users can delete own blocks"
  ON public.blocked_users FOR DELETE
  USING (auth.uid() = blocker_id);

-- 3. reports 테이블 생성
CREATE TABLE IF NOT EXISTS public.reports (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id  uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  reported_id  uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  reason       text NOT NULL DEFAULT '',
  created_at   timestamptz DEFAULT now()
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own reports"
  ON public.reports FOR INSERT
  WITH CHECK (auth.uid() = reporter_id);

-- 4. Supabase Storage 버킷 생성 (avatars)
-- Storage > New Bucket > 이름: avatars, Public: ON
-- 아래 SQL은 버킷 생성 후 정책 설정입니다
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Anyone can view avatars"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'avatars');

CREATE POLICY "Authenticated users can upload avatars"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');

CREATE POLICY "Users can update own avatar"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete own avatar"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);
