-- KoriBridge 데이터베이스 스키마
-- Supabase Dashboard → SQL Editor 에서 실행하세요

-- profiles 테이블 (사용자 프로필)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  display_name text not null,
  nationality text not null,
  native_language text not null,
  learning_language text not null,
  language_level text default '초급',
  interests text[] default '{}',
  bio text default '',
  avatar_url text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Row Level Security 활성화
alter table public.profiles enable row level security;

-- 정책: 본인 프로필만 수정 가능
create policy "Users can view all profiles"
  on public.profiles for select
  using (true);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- messages 테이블
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users on delete cascade not null,
  receiver_id uuid references auth.users on delete cascade not null,
  content text not null,
  created_at timestamptz default now(),
  edited_at timestamptz,
  read_at timestamptz
);

alter table public.messages enable row level security;

create policy "Users can insert messages"
  on public.messages for insert
  with check (auth.uid() = sender_id);

create policy "Users can select messages"
  on public.messages for select
  using (
    auth.uid() = sender_id or auth.uid() = receiver_id
  );

create policy "Users can update message read status"
  on public.messages for update
  using (auth.uid() = receiver_id);

create policy "Users can update own messages"
  on public.messages for update
  using (auth.uid() = sender_id);

-- 메시지 UPDATE 컬럼 제한
-- 수신자: read_at만 변경 가능
-- 발신자: content, edited_at만 변경 가능
create or replace function public.prevent_unsafe_message_update()
returns trigger
language plpgsql
as $$
declare
  actor uuid := auth.uid();
begin
  if actor is null then
    raise exception 'Authentication required';
  end if;

  if actor = old.receiver_id and actor <> old.sender_id then
    if (to_jsonb(new) - 'read_at') <> (to_jsonb(old) - 'read_at') then
      raise exception 'Receivers can only update read_at';
    end if;
    return new;
  end if;

  if actor = old.sender_id then
    if (to_jsonb(new) - ARRAY['content', 'edited_at']) <> (to_jsonb(old) - ARRAY['content', 'edited_at']) then
      raise exception 'Senders can only update content and edited_at';
    end if;
    return new;
  end if;

  raise exception 'Not allowed to update this message';
end;
$$;

drop trigger if exists prevent_unsafe_message_update_on_messages on public.messages;
create trigger prevent_unsafe_message_update_on_messages
  before update on public.messages
  for each row
  execute function public.prevent_unsafe_message_update();

-- blocked_users 테이블
create table public.blocked_users (
  id bigint generated by default as identity primary key,
  blocker_id uuid references auth.users on delete cascade not null,
  blocked_id uuid references auth.users on delete cascade not null,
  created_at timestamptz default now()
);

-- favorites 테이블
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  partner_id uuid references auth.users on delete cascade not null,
  created_at timestamptz default now(),
  unique (user_id, partner_id)
);

alter table public.blocked_users enable row level security;

create policy "Users can insert blocked users"
  on public.blocked_users for insert
  with check (auth.uid() = blocker_id);

create policy "Users can select blocked users"
  on public.blocked_users for select
  using (auth.uid() = blocker_id);

create policy "Users can delete blocked users"
  on public.blocked_users for delete
  using (auth.uid() = blocker_id);

-- updated_at 자동 갱신 트리거
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger on_profile_updated
  before update on public.profiles
  for each row execute procedure public.handle_updated_at();

-- Supabase Realtime 활성화
do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;

-- 신규 가입 시 profiles 행 자동 생성 (선택사항)
-- 회원가입 직후 프로필 등록 페이지로 이동하는 방식이므로 생략 가능
