-- 1. 신고 테이블 생성
CREATE TABLE IF NOT EXISTS public.reports (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id  uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  reported_id  uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  reason       text NOT NULL,
  detail       text,
  status       text DEFAULT 'pending', -- pending, resolved, rejected
  created_at   timestamptz DEFAULT now()
);

-- 2. 차단 테이블 생성
CREATE TABLE IF NOT EXISTS public.blocked_users (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocker_id   uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  blocked_id   uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  created_at   timestamptz DEFAULT now(),
  UNIQUE (blocker_id, blocked_id)
);

-- RLS 활성화
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_users ENABLE ROW LEVEL SECURITY;

-- 본인의 차단 목록 및 신고만 조회/생성 가능
CREATE POLICY "Users can manage own blocks" ON public.blocked_users
  FOR ALL USING (auth.uid() = blocker_id);

CREATE POLICY "Users can insert own reports" ON public.reports
  FOR INSERT WITH CHECK (auth.uid() = reporter_id);

-- 3. 기존 profiles 조회 정책 수정 (차단 유저 제외)
DROP POLICY IF EXISTS "Users can view all profiles" ON public.profiles;

CREATE POLICY "Users can view profiles excluding blocked"
  ON public.profiles FOR SELECT
  USING (
    id NOT IN (
      SELECT blocked_id FROM public.blocked_users WHERE blocker_id = auth.uid()
    )
  );
